### ISSUE TITLE
Failed loading native library

### ISSUE THREAD

**Issue by prgrewal** [awslabs/amazon-kinesis-video-streams-producer-sdk-java#31]
I am having the same issue as others in loading the native library.
Steps taken:
Using OSX,
ran the install-script from amazon-kinesis-video-streams-producer-sdk-cpp/kinesis-video-native-build
ran the java-install-script from amazon-kinesis-video-streams-producer-sdk-cpp/kinesis-video-native-build

Using intelliJ IDEA, in idea.vmoptions set
-Djava.library.path=/absolute/path/to/amazon-kinesis-video-streams-producer-sdk-cpp/kinesis-video-native-build

In https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-java/blob/master/src/main/java/com/amazonaws/kinesisvideo/producer/jni/NativeLibraryLoader.java#L55
is set to 
System.load('/absolute/path/to/amazon-kinesis-video-streams-producer-sdk-cpp/kinesis-video-native-build')

Then in intelliJ editor right clicked DemoAppMain and clicked run
it then outputs the following error:
/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/bin/java "-javaagent:/Applications/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar=49586:/Applications/IntelliJ IDEA CE.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/jaccess.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/lib/packager.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/lib/tools.jar:/Users/romangrewal/t1cgacademy/sp14/t1-academy/kinesis/java/amazon-kinesis-video-streams-producer-sdk-java/target/classes:/Users/romangrewal/.m2/repository/com/amazonaws/aws-java-sdk-core/1.11.172/aws-java-sdk-core-1.11.172.jar:/Users/romangrewal/.m2/repository/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar:/Users/romangrewal/.m2/repository/org/apache/httpcomponents/httpclient/4.5.2/httpclient-4.5.2.jar:/Users/romangrewal/.m2/repository/org/apache/httpcomponents/httpcore/4.4.4/httpcore-4.4.4.jar:/Users/romangrewal/.m2/repository/commons-codec/commons-codec/1.9/commons-codec-1.9.jar:/Users/romangrewal/.m2/repository/software/amazon/ion/ion-java/1.0.2/ion-java-1.0.2.jar:/Users/romangrewal/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.6.7.1/jackson-databind-2.6.7.1.jar:/Users/romangrewal/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.6.0/jackson-annotations-2.6.0.jar:/Users/romangrewal/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.6.7/jackson-core-2.6.7.jar:/Users/romangrewal/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-cbor/2.6.7/jackson-dataformat-cbor-2.6.7.jar:/Users/romangrewal/.m2/repository/joda-time/joda-time/2.8.1/joda-time-2.8.1.jar:/Users/romangrewal/.m2/repository/com/google/inject/guice/4.0/guice-4.0.jar:/Users/romangrewal/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar:/Users/romangrewal/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar:/Users/romangrewal/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar:/Users/romangrewal/.m2/repository/com/google/guava/guava/21.0/guava-21.0.jar:/Users/romangrewal/.m2/repository/com/google/code/findbugs/annotations/2.0.3/annotations-2.0.3.jar:/Users/romangrewal/.m2/repository/org/apache/commons/commons-lang3/3.4/commons-lang3-3.4.jar:/Users/romangrewal/.m2/repository/com/google/code/gson/gson/2.8.2/gson-2.8.2.jar:/Users/romangrewal/.m2/repository/javax/measure/jsr-275/0.9.1/jsr-275-0.9.1.jar:/Users/romangrewal/.m2/repository/com/google/inject/extensions/guice-multibindings/4.0/guice-multibindings-4.0.jar:/Users/romangrewal/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar:/Users/romangrewal/.m2/repository/com/amazonaws/aws-java-sdk-kinesisvideo/1.11.255/aws-java-sdk-kinesisvideo-1.11.255.jar:/Users/romangrewal/.m2/repository/io/netty/netty-codec-http/4.1.17.Final/netty-codec-http-4.1.17.Final.jar:/Users/romangrewal/.m2/repository/io/netty/netty-codec/4.1.17.Final/netty-codec-4.1.17.Final.jar:/Users/romangrewal/.m2/repository/io/netty/netty-handler/4.1.17.Final/netty-handler-4.1.17.Final.jar:/Users/romangrewal/.m2/repository/io/netty/netty-buffer/4.1.17.Final/netty-buffer-4.1.17.Final.jar:/Users/romangrewal/.m2/repository/io/netty/netty-common/4.1.17.Final/netty-common-4.1.17.Final.jar:/Users/romangrewal/.m2/repository/io/netty/netty-transport/4.1.17.Final/netty-transport-4.1.17.Final.jar:/Users/romangrewal/.m2/repository/io/netty/netty-resolver/4.1.17.Final/netty-resolver-4.1.17.Final.jar:/Users/romangrewal/.m2/repository/com/amazonaws/jmespath-java/1.11.255/jmespath-java-1.11.255.jar com.amazonaws.kinesisvideo.demoapp.DemoAppMain

objc[707]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/bin/java (0x10ff0f4c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x10ff9b4e0). One of the two will be used. Which one is undefined.
WARN / KinesisVideo: Unsatisfied link error. Directly loading native library .so.
WARN / KinesisVideo: Unsatisfied link error. Directly loading native library .dylib.
WARN / KinesisVideo: Unsatisfied link error. Directly loading native library .dll.
WARN / KinesisVideo: Unsatisfied link error. Directly loading native library libKinesisVideoProducerJNI.so.
WARN / KinesisVideo: Unsatisfied link error. Directly loading native library libKinesisVideoProducerJNI.dylib.
WARN / KinesisVideo: Unsatisfied link error. Directly loading native library libKinesisVideoProducerJNI.dll.
ERROR / KinesisVideo: 2018-03-07T17:43Z T1: EXCEPTION: UnsatisfiedLinkError: Unsatisfied link error. Loading native library KinesisVideoProducerJNI failed with java.lang.UnsatisfiedLinkError: no KinesisVideoProducerJNI in java.library.path: no KinesisVideoProducerJNI in java.library.path
Exception in thread "main" java.lang.RuntimeException: com.amazonaws.kinesisvideo.producer.ProducerException: Failed loading native library
	at com.amazonaws.kinesisvideo.demoapp.DemoAppMain.main(DemoAppMain.java:45)
Caused by: com.amazonaws.kinesisvideo.producer.ProducerException: Failed loading native library
	at com.amazonaws.kinesisvideo.producer.jni.NativeKinesisVideoProducerJni.initializeLibrary(NativeKinesisVideoProducerJni.java:1069)
	at com.amazonaws.kinesisvideo.producer.jni.NativeKinesisVideoProducerJni.create(NativeKinesisVideoProducerJni.java:220)
	at com.amazonaws.kinesisvideo.producer.jni.NativeKinesisVideoProducerJni.create(NativeKinesisVideoProducerJni.java:193)
	at com.amazonaws.kinesisvideo.client.NativeKinesisVideoClient.initialize(NativeKinesisVideoClient.java:112)
	at com.amazonaws.kinesisvideo.java.client.KinesisVideoJavaClientFactory.createKinesisVideoClient(KinesisVideoJavaClientFactory.java:107)
	at com.amazonaws.kinesisvideo.java.client.KinesisVideoJavaClientFactory.createKinesisVideoClient(KinesisVideoJavaClientFactory.java:80)
	at com.amazonaws.kinesisvideo.demoapp.DemoAppMain.main(DemoAppMain.java:31)

Process finished with exit code 1

**Comment by unicornss** [comment]
can you tell us the files under the directory `/absolute/path/to/amazon-kinesis-video-streams-producer-sdk-cpp/kinesis-video-native-build` by 
```
ls -l /absolute/path/to/amazon-kinesis-video-streams-producer-sdk-cpp/kinesis-video-native-build
```

**Comment by romangrewal** [comment]
-rw-r--r--   1 romangrewal  staff    14093 Mar  7 15:56 CMakeCache.txt
drwxr-xr-x  19 romangrewal  staff      608 Mar  7 16:22 CMakeFiles
-rw-r--r--   1 romangrewal  staff    15756 Mar  7 15:13 CMakeLists.txt
-rw-r--r--   1 romangrewal  staff   390972 Mar  7 16:22 Makefile
-rw-r--r--   1 romangrewal  staff     1561 Mar  7 15:56 cmake_install.cmake
drwxr-xr-x  47 romangrewal  staff     1504 Mar  7 15:48 downloads
-r-xr-xr-x   1 romangrewal  staff    21391 Mar  7 15:13 install-script
-rwxr-xr-x   1 romangrewal  staff      845 Mar  7 15:13 java-install-script
-rwxr-xr-x   1 romangrewal  staff   121756 Mar  7 15:57 kinesis_video_gstreamer_sample_app
-rwxr-xr-x   1 romangrewal  staff   111692 Mar  7 15:57 kinesis_video_gstreamer_sample_rtsp_app
-rwxr-xr-x   1 romangrewal  staff   259852 Mar  7 15:57 libKinesisVideoProducerJNI.dylib
-rwxr-xr-x   1 romangrewal  staff  1373260 Mar  7 15:57 libproducer.dylib
-rwxr-xr-x   1 romangrewal  staff     2400 Mar  7 15:13 min-install-script
drwxr-xr-x  19 romangrewal  staff      608 Mar  7 15:13 samples
-rwxr-xr-x   1 romangrewal  staff  3427700 Mar  7 15:57 start
-rw-r--r--   1 romangrewal  staff   143289 Mar  7 16:02 test_h264_jpg.mkv
-rw-r--r--   1 romangrewal  staff   143305 Mar  7 16:02 test_jpeg.mkv

**Comment by zhiyua-git** [comment]
Can you tell us the linkage on libKinesisVideoProducerJNI by 
```
otool -L /absolute/path/to/amazon-kinesis-video-streams-producer-sdk-cpp/kinesis-video-native-build/libKinesisVideoProducerJNI.dylib
```

You can try to re-create libKinesisVideoProducerJNI.dylib meanwhile by 
```
rm -rf CMakeFiles CMakeCache.txt libKinesisVideoProducerJNI.dylib
./java-install-script
```

**Comment by romangrewal** [comment]
otool -L libKinesisVideoProducerJNI.dylib
outputs:
libKinesisVideoProducerJNI.dylib:
	@rpath/libKinesisVideoProducerJNI.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)

recreating libKinesisVideoProducerJNI.dylib produced the same unsatisfied link error

**Comment by zhiyua-git** [comment]
Everything looks correct. 

Can you set in https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-java/blob/master/src/main/java/com/amazonaws/kinesisvideo/producer/jni/NativeLibraryLoader.java#L55
to
System.load('/absolute/path/to/amazon-kinesis-video-streams-producer-sdk-cpp/kinesis-video-native-build/libKinesisVideoProducerJNI.dylib') 
as a workaround now? 

You need to provide full path including file name inside direct library load.

**Comment by romangrewal** [comment]
The workaround worked with the full path including the file name.

**Comment by romangrewal** [comment]
Following the example here:
https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-java/issues/10

I was able to get all the libraries built and stream from my webcam to kinesis. However, on the kinesis portal, it says:

<img width="1172" alt="screen shot 2018-03-13 at 5 04 28 pm" src="https://user-images.githubusercontent.com/15803176/37369836-ac50d19a-26e0-11e8-867c-f69242ec9d76.png">

Perhaps there is an issue with the codecPrivateData byte array?
Here:
https://stackoverflow.com/questions/32490988/smooth-streaming-codec-private-data
It says that the NAL_START_CODE for AVC1 should be 00,00,00,01 but I am seeing 01,42,00,20.
Changing it to 00,00,00,01 gives me the error:

<img width="1153" alt="screen shot 2018-03-13 at 5 10 11 pm" src="https://user-images.githubusercontent.com/15803176/37370068-793814d4-26e1-11e8-9b37-d3540a15edb8.png">

**Comment by MushMal** [comment]
@romangrewal I would like to provide some information before suggesting the steps. This is assuming the producer is streaming OK.

* Codec Private Data is codec specific bits. In case of H264 this is SPS and PPS information.
* Both frames and the CPD can be in Annex-B format or AvCC format - those are different for frames vs. the CPD.
* Console playback can only consume AvCC format frames and codec private data.
* Many encoders will produce AvCC format.

Now, with this in mind, we have a set of flags that control the adaptation behavior defined in StreamInfo.java::NalAdaptationFlags. You can use the combination of frame and CPD depending on your encoders output (NAL_ADAPTATION_ANNEXB_CPD_AND_FRAME_NALS).

Please try and let us know so we can eliminate the CPD.

**Comment by romangrewal** [comment]
When
StreamInfo.NalAdaptationFlags.NAL_ADAPTATION_FLAG_NONE
is changed to
StreamInfo.NalAdaptationFlags.NAL_ADAPTATION_ANNEXB_CPD_AND_FRAME_NALS

the console outputs the error
Exception in thread "main" java.lang.RuntimeException: com.amazonaws.kinesisvideo.producer.ProducerException: Failed to create a stream.
	at com.amazonaws.kinesisvideo.demoapp.DemoAppMain.main(DemoAppMain.java:60)
Caused by: com.amazonaws.kinesisvideo.producer.ProducerException: Failed to create a stream.
	at com.amazonaws.kinesisvideo.producer.jni.NativeKinesisVideoProducerJni.createKinesisVideoStream(Native Method)
	at com.amazonaws.kinesisvideo.producer.jni.NativeKinesisVideoProducerJni.createStream(NativeKinesisVideoProducerJni.java:318)
	at com.amazonaws.kinesisvideo.producer.jni.NativeKinesisVideoProducerJni.createStreamSync(NativeKinesisVideoProducerJni.java:345)
	at com.amazonaws.kinesisvideo.client.NativeKinesisVideoClient.registerMediaSource(NativeKinesisVideoClient.java:121)
	at com.amazonaws.kinesisvideo.demoapp.DemoAppMain.main(DemoAppMain.java:53)

**Comment by MushMal** [comment]
You mean the application fails with this error. This is odd - I don't see any error code that will tell me what's causing the stream object creation failure. 

* Can you capture all of the logs
* Could you capture and include the CPD bits so I can see what format those are in

**Comment by romangrewal** [comment]
The entire log from the console:

/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/bin/java "-javaagent:/Applications/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar=51469:/Applications/IntelliJ IDEA CE.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/jaccess.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/lib/packager.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/lib/tools.jar:/Users/romangrewal/t1cgacademy/sp15/t1-academy/kinesis/java/amazon-kinesis-video-streams-producer-sdk-java/target/classes:/Users/romangrewal/.m2/repository/org/jboss/netty/netty/3.2.0.Final/netty-3.2.0.Final.jar:/Users/romangrewal/.m2/repository/com/github/sarxos/webcam-capture/0.3.12/webcam-capture-0.3.12.jar:/Users/romangrewal/.m2/repository/com/nativelibs4java/bridj/0.7.0/bridj-0.7.0.jar:/Users/romangrewal/.m2/repository/org/slf4j/slf4j-api/1.7.2/slf4j-api-1.7.2.jar:/Users/romangrewal/.m2/repository/xuggle/xuggle-xuggler/5.4/xuggle-xuggler-5.4.jar:/Users/romangrewal/.m2/repository/com/amazonaws/aws-java-sdk-core/1.11.172/aws-java-sdk-core-1.11.172.jar:/Users/romangrewal/.m2/repository/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar:/Users/romangrewal/.m2/repository/org/apache/httpcomponents/httpclient/4.5.2/httpclient-4.5.2.jar:/Users/romangrewal/.m2/repository/org/apache/httpcomponents/httpcore/4.4.4/httpcore-4.4.4.jar:/Users/romangrewal/.m2/repository/commons-codec/commons-codec/1.9/commons-codec-1.9.jar:/Users/romangrewal/.m2/repository/software/amazon/ion/ion-java/1.0.2/ion-java-1.0.2.jar:/Users/romangrewal/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.6.7.1/jackson-databind-2.6.7.1.jar:/Users/romangrewal/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.6.0/jackson-annotations-2.6.0.jar:/Users/romangrewal/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.6.7/jackson-core-2.6.7.jar:/Users/romangrewal/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-cbor/2.6.7/jackson-dataformat-cbor-2.6.7.jar:/Users/romangrewal/.m2/repository/joda-time/joda-time/2.8.1/joda-time-2.8.1.jar:/Users/romangrewal/.m2/repository/com/google/inject/guice/4.0/guice-4.0.jar:/Users/romangrewal/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar:/Users/romangrewal/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar:/Users/romangrewal/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar:/Users/romangrewal/.m2/repository/com/google/guava/guava/21.0/guava-21.0.jar:/Users/romangrewal/.m2/repository/com/google/code/findbugs/annotations/2.0.3/annotations-2.0.3.jar:/Users/romangrewal/.m2/repository/org/apache/commons/commons-lang3/3.4/commons-lang3-3.4.jar:/Users/romangrewal/.m2/repository/com/google/code/gson/gson/2.8.2/gson-2.8.2.jar:/Users/romangrewal/.m2/repository/javax/measure/jsr-275/0.9.1/jsr-275-0.9.1.jar:/Users/romangrewal/.m2/repository/com/google/inject/extensions/guice-multibindings/4.0/guice-multibindings-4.0.jar:/Users/romangrewal/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar:/Users/romangrewal/.m2/repository/com/amazonaws/aws-java-sdk-kinesisvideo/1.11.255/aws-java-sdk-kinesisvideo-1.11.255.jar:/Users/romangrewal/.m2/repository/io/netty/netty-codec-http/4.1.17.Final/netty-codec-http-4.1.17.Final.jar:/Users/romangrewal/.m2/repository/io/netty/netty-codec/4.1.17.Final/netty-codec-4.1.17.Final.jar:/Users/romangrewal/.m2/repository/io/netty/netty-handler/4.1.17.Final/netty-handler-4.1.17.Final.jar:/Users/romangrewal/.m2/repository/io/netty/netty-buffer/4.1.17.Final/netty-buffer-4.1.17.Final.jar:/Users/romangrewal/.m2/repository/io/netty/netty-common/4.1.17.Final/netty-common-4.1.17.Final.jar:/Users/romangrewal/.m2/repository/io/netty/netty-transport/4.1.17.Final/netty-transport-4.1.17.Final.jar:/Users/romangrewal/.m2/repository/io/netty/netty-resolver/4.1.17.Final/netty-resolver-4.1.17.Final.jar:/Users/romangrewal/.m2/repository/com/amazonaws/jmespath-java/1.11.255/jmespath-java-1.11.255.jar com.amazonaws.kinesisvideo.demoapp.DemoAppMain
objc[9747]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/bin/java (0x1039b84c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x1059f54e0). One of the two will be used. Which one is undefined.
INFO / KinesisVideo: Initializing Kinesis Video client
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.RuntimeException: com.amazonaws.kinesisvideo.producer.ProducerException: Failed to create a stream.
	at com.amazonaws.kinesisvideo.demoapp.DemoAppMain.main(DemoAppMain.java:60)
Caused by: com.amazonaws.kinesisvideo.producer.ProducerException: Failed to create a stream.
	at com.amazonaws.kinesisvideo.producer.jni.NativeKinesisVideoProducerJni.createKinesisVideoStream(Native Method)
	at com.amazonaws.kinesisvideo.producer.jni.NativeKinesisVideoProducerJni.createStream(NativeKinesisVideoProducerJni.java:318)
	at com.amazonaws.kinesisvideo.producer.jni.NativeKinesisVideoProducerJni.createStreamSync(NativeKinesisVideoProducerJni.java:345)
	at com.amazonaws.kinesisvideo.client.NativeKinesisVideoClient.registerMediaSource(NativeKinesisVideoClient.java:121)
	at com.amazonaws.kinesisvideo.demoapp.DemoAppMain.main(DemoAppMain.java:53)

Java_com_amazonaws_kinesisvideo_producer_jni_NativeKinesisVideoProducerJni_createKinesisVideoClient(): Enter
Java_com_amazonaws_kinesisvideo_producer_jni_NativeKinesisVideoProducerJni_createKinesisVideoClient(): Creating Kinesis Video client.
createKinesisVideoClient(): Creating Kinesis Video Client
heapInitialize(): Initializing native heap with limit size 1073741824, spill ratio 90% and flags 0x00000001
heapInitialize(): Creating AIV heap.
heapInitialize(): Heap is initialized OK
Java_com_amazonaws_kinesisvideo_producer_jni_NativeKinesisVideoProducerJni_createKinesisVideoClient(): Leave
Java_com_amazonaws_kinesisvideo_producer_jni_NativeKinesisVideoProducerJni_createDeviceResultEvent(): Enter
Java_com_amazonaws_kinesisvideo_producer_jni_NativeKinesisVideoProducerJni_createDeviceResultEvent(): create device event for handle 0x00007fd75704f000.
createDeviceResultEvent(): Create device result event.
Java_com_amazonaws_kinesisvideo_producer_jni_NativeKinesisVideoProducerJni_createDeviceResultEvent(): Leave
Java_com_amazonaws_kinesisvideo_producer_jni_NativeKinesisVideoProducerJni_createKinesisVideoStream(): Enter
Java_com_amazonaws_kinesisvideo_producer_jni_NativeKinesisVideoProducerJni_createKinesisVideoStream(): Creating Kinesis Video stream.
createKinesisVideoStream(): Creating Kinesis Video Stream.
createKinesisVideoStream(): Failed to create a stream with status code 0x32000010
throwNativeException(): Throwing com/amazonaws/kinesisvideo/producer/ProducerException with message: Failed to create a stream.
Java_com_amazonaws_kinesisvideo_producer_jni_NativeKinesisVideoProducerJni_createKinesisVideoStream(): Leave
Process finished with exit code 130 (interrupted by signal 2: SIGINT)

The CPD bits are defined in the code as:
byte[] codecPrivateData = { 0x01, 0x42, 0x00, 0x20, (byte) 0xff, (byte) 0xe1, 0x00, 0x23, 0x27, 0x42, 0x00, 0x20, (byte) 0x89, (byte) 0x8b, 0x60, 0x28, 0x02, (byte) 0xdd, (byte) 0x80, (byte) 0x9e, 0x00, 0x00, 0x4e, 0x20, 0x00, 0x0f, 0x42, 0x41, (byte) 0xc0, (byte) 0xc0, 0x01, 0x77, 0x00, 0x00, 0x5d, (byte) 0xc1, 0x7b, (byte) 0xdf, 0x07, (byte) 0xc2, 0x21, 0x1b, (byte) 0x80, 0x01, 0x00, 0x04, 0x28, (byte) 0xce, 0x1f, 0x20 };

**Comment by MushMal** [comment]
`createKinesisVideoStream(): Failed to create a stream with status code 0x32000010`

This means that the CPD has invalid AnnexB format NALu to adapt.

Looking at the CPD you've provided I can see that it's already in the AVCC format so you don't need to adapt the CPD.

Please check the frames whether they are in Annex-B format and need to be adapted. You can simply check whether the frame starts with the Annex-B start code of 001 or 0001. If so, it needs to be adapted.

**Comment by romangrewal** [comment]
The first 4 bytes of a video frame are 
0x00 0x00 0x00 0x01

When we pass in 
StreamInfo.NalAdaptationFlags.NAL_ADAPTATION_ANNEXB_NALS 
to withNalAdaptationFlags()
it reads and displays the first frame of the video in AWS kinesis but then displays
<img width="1069" alt="screen shot 2018-03-14 at 12 50 51 pm" src="https://user-images.githubusercontent.com/15803176/37417388-8ec52ab2-2786-11e8-81ee-e143dfd57a82.png">

**Comment by MushMal** [comment]
@romangrewal It seems that your CPD is AvCC format but the frames are in Annex-B, in which case you were right in selecting the NAL_ADAPTATION_ANNEXB_NALS flag.

What's strange is that the browsers decoder returns an error. Let me try to dig a little more info for you but can I ask you to do the following:

* Describe your end-to-end scenario - what are you trying to achieve and what's your media source. Perhaps we could reproduce it here.
* Could you please include the full logs from your run with this flag so we can see whether there is any issue on the producer side.
* It's also possible that somehow the frames get corrupted. Could you capture your stream and see if you can play it back using VLC or some other tool?

**Comment by MushMal** [comment]
One more thing.. The error that's shown indicates the fragment size of 1.1Kb - I would expect the fragment size to be much larger for h264 video - a P or a B frame can be this small but not the entire fragment. Can you share more info?

**Comment by zhiyua-git** [comment]
Close issue as library loading issue is resolved. Please open another thread for other issues.

**Comment by TechReporter** [comment]
UnsatisfiedLinkError: com.amazonaws.kinesisvideo.producer.jni.NativeKinesisVideoProducerJni.getNativeLibraryVersion()Ljava/lang/String
I am following this workspace https://github.com/backdoorcodr/amazon-kinesis-video-streams-producer-sdk-java
Expectation is to run kinesis video stream using webcam in java.
Please help
