### ISSUE TITLE
Undefined methods 

### ISSUE THREAD

**Issue by backdoorcodr** [awslabs/amazon-kinesis-video-streams-producer-sdk-java#6]
Hello,

I have followed the README.md of the [cpp-sdk](https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp) to build the C++ wrapper for JNI on my linux system. Access key and access key id have also been specified to my JVM environment. 

I download this java project and it starts to download the dependencies specified in pom.xml and builds. However,  after maven have downloaded necessary libraries and built the workspace I get a number of methods to be undefined. Screenshot has been attached. Are there any missing dependencies in the pom.xml? How this can be resolved? 
![screenshot from 2017-12-09 21-39-52](https://user-images.githubusercontent.com/34404238/33799321-85adfef6-dd29-11e7-8ab7-d5b27fb655f8.png)

**Comment by zhiyua-git** [comment]
Hi,

This issue is likely caused by missing lombok dependency. You can check your pom.xml and try to update your maven dependencies.

For you Eclipse case, uncheck option in **Window -> Preferences -> Maven -> Do not automatically update dependencies from remote repositories**. This should be able to help you get those dependencies.

**Comment by backdoorcodr** [comment]
@zhiyua-git perfect. That resolved this issue. Many thanks :+1: :beer:
